### ISSUE TITLE
Store unmapped data on models

### ISSUE THREAD

**Issue by benito103e** [GitLabPHP/Client#197]
For example Model/Project doesn't contain property for permissions.
https://docs.gitlab.com/ce/api/projects.html#get-single-project

Is it possible, for missing properties, to store data on a specific array property.

On AbstractModel::setData()
```php
if (in_array($field, static::$properties)) {
   $this->data[$field] = $value;
}
$this->allData[$field] = $value;
```

It would be a fallback when the Gitlab API evolves faster than this client.

**Comment by m4tthumphrey** [comment]
I think Models need to be refactored. Gitlab has envolved heavily since I started this project, some sort of magic getter/setter using dot notation might be better for Models.

**Comment by fbourigault** [comment]
I have in mind to refactor models by generating them usign https://github.com/janephp/jane. Our main job would be to write JSON Schema files describing Gitlab models.

An advantage to this is if https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/2397 succeed, we will be able to switch to their description of entities and even go further by generating the whole library code using https://github.com/janephp/jane-openapi!

**Comment by benito103e** [comment]
@fbourigault this is a good way of approaching the problem.
