### ISSUE TITLE
List user's projects

### ISSUE THREAD

**Issue by soullivaneuh** [GitLabPHP/Client#256]
I don't see anything in this SDK to call this API resource: https://docs.gitlab.com/ee/api/projects.html#list-user-projects

Am I right?

**Comment by fbourigault** [comment]
It's not yet implemented. Feel free to open a PR to add it.

**Comment by Soullivaneuh** [comment]
@fbourigault Why closing this issue in that case?

**Comment by fbourigault** [comment]
That's a good question!
