### ISSUE TITLE
Trouble passing state parameter

### ISSUE THREAD

**Issue by dozer55** [GitLabPHP/Client#258]
Passing a state parameter of closed, but receiving complete list instead of filtered list. Here's what I'm doing:

`$project = $client->api('issues')->show($projectid, array(
    'state' => 'closed',
  ));`

**Comment by GrahamCampbell** [comment]
`show` is to fetch a single issue. You are gonna want the `all` method.

**Comment by GrahamCampbell** [comment]
@dozer55 here's an example:

```php
$issues = $client->issues()->all($projectid, ['state' => 'closed']);
```

PS The `api('issues')` method will be deprecated in the next release: use `issues()` instead, like in the example.
