### ISSUE TITLE
Session API had removed in 10.2.0 ,and support impersonation token

### ISSUE THREAD

**Issue by woodylan** [GitLabPHP/Client#330]
Session API had removed in 10.2.0 ,and support impersonation token，but php-gitlab-api do not support impersonation token。

https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CHANGELOG.md#1020-2017-11-22
https://docs.gitlab.com/ce/api/users.html#create-an-impersonation-token

**Comment by GrahamCampbell** [comment]
This has been available since 9.10.0. :)
