### ISSUE TITLE
Add Support for Wiki 

### ISSUE THREAD

**Issue by oemunoz** [GitLabPHP/Client#335]
Is planned some support for the wiki pages?

[https://docs.gitlab.com/ee/api/wikis.html](https://docs.gitlab.com/ee/api/wikis.html)

Tnks!!!

**Comment by hanwenbo** [comment]
Tnks!!! Add Support for Wiki

**Comment by m1guelpf** [comment]
Feel free to submit a PR :)

**Comment by morinluc0** [comment]
Started working on a PR for this request,

I still need to create test cases and functions to perform actions on the wiki from the project class.

**Comment by GrahamCampbell** [comment]
Implemented. Was available since 9.17.0. :)

**Comment by GrahamCampbell** [comment]
Thank you @morinluc0. 🚀
