### ISSUE TITLE
Possible to set 'Visibility Level' for a Group?

### ISSUE THREAD

**Issue by geerlingguy** [GitLabPHP/Client#374]
When I create a Group in GitLab:

```php
$client->api('groups')->create($group_name, $group_path);
```

It is created with the default Visibility Level "Private". If I want to create it with Visibility Level "Internal" or "Public", is that currently possible?

Groups API: https://docs.gitlab.com/ee/api/groups.html#new-group

|Parameter|Type|Required|Description|
|---|---|---|---|
|`visibility`|string|no|The group’s visibility. Can be `private`, `internal`, or `public`.|

**Comment by GrahamCampbell** [comment]
Yes.

**Comment by GrahamCampbell** [comment]
This is the doc for that method:

```
     * @param string $name
     * @param string $path
     * @param string $description
     * @param string $visibility
     * @param bool   $lfs_enabled
     * @param bool   $request_access_enabled
     * @param int    $parent_id
     * @param int    $shared_runners_minutes_limit
```
