### ISSUE TITLE
Add support for retrieving inherited group/project members

### ISSUE THREAD

**Issue by GMTA** [GitLabPHP/Client#377]
I don't think there is a way to retrieve the inherited group or project members through the API or models. I'm talking about these paths:

```
/api/v4/projects/:id/members/all
/api/v4/groups/:id/members/all
```

These return the inherited (flattened) member list instead of the directly assigned members.

**Comment by m1guelpf** [comment]
Feel free to make a PR!

**Comment by GMTA** [comment]
@m1guelpf I'm not sure how you would like to see the API for that. New methods called `membersAll` or `allMembers`? Add options to `members`?

**Comment by sluc23** [comment]
@m1guelpf / @GMTA 
please checkout #409
