### ISSUE TITLE
How to retrieve member in group with id?

### ISSUE THREAD

**Issue by outofcontrol** [GitLabPHP/Client#404]
Is it possible to retrieve one group member using the Group and project members API:

    GET /groups/:id/members/:user_id

The closest I can get is (using Laravel):

    GitLab::api('groups')->members($group['id'], ['query'=>':username']);

**Comment by donkidd** [comment]
@outofcontrol How did you end up solving this?  That seems like a way to get a member of a group.  Were you looking for another way to do this?

**Comment by GrahamCampbell** [comment]
>  Were you looking for another way to do this?

@donkidd, yes @outofcontrol was, as they said: 

> Is it possible to retrieve one group member using the Group and project members API:
> 
>     GET /groups/:id/members/:user_id
> 

---

@outofcontrol We'd happily accept a PR with tests to add this endpoint to our client. :)

**Comment by allcreatures** [comment]
> > Were you looking for another way to do this?
> 
> @donkidd, yes @outofcontrol was, as they said:
> 
> > Is it possible to retrieve one group member using the Group and project members API:
> > ```
> > GET /groups/:id/members/:user_id
> > ```
> 
> @outofcontrol We'd happily accept a PR with tests to add this endpoint to our client. :)

For what it is worth, I didn't mean to ignore you @GrahamCampbell. The stale bot reminded me of this issue. Fortunate for us I found a work around, sadly for this issue I now forget what it was and right now I am strangled by in work.

**Comment by YKWeyer** [comment]
@outofcontrol I think since this issue was created, it was added with `$client->groups()->member($group_id, $user_id)`
 (for versions `9.18.0` and later)

https://github.com/GitLabPHP/Client/blob/f927ee3aad158b421437d3182a2f9d24f76f8ba5/src/Api/Groups.php#L153

**Comment by allcreatures** [comment]
@YKWeyer Thank you. I will take a look. Perhaps okay to close this issue now that this is completed.
