### ISSUE TITLE
No time entry support for merge requests

### ISSUE THREAD

**Issue by Cysioland** [GitLabPHP/Client#421]
No support for listing MR's time entries and updating them

**Comment by Cysioland** [comment]
Working on something that  needs it, so I might actually do something about it

**Comment by m1guelpf** [comment]
Feel free to PR!

**Comment by Cysioland** [comment]
Need to clean it up first, as a similar thing would be needed for issues, probably (the updating part)

**Comment by GrahamCampbell** [comment]
Done. Will be available in the next release. :)
