### ISSUE TITLE
Create Merge Request - missing parameters

### ISSUE THREAD

**Issue by svilborg** [GitLabPHP/Client#435]
Create Merge Request endpoint doesn't support some extra parameters like `remove_source_branch`, `squash`
 
https://docs.gitlab.com/ee/api/merge_requests.html#create-mr

**Comment by GrahamCampbell** [comment]
The codes does support them, it just doesn't document them. You can pass anything you like in the parameters array.

**Comment by GrahamCampbell** [comment]
This is supported already, using the parameters array. Passing explicit params is deprecated, and will be removed in v10.
