### ISSUE TITLE
Merge Request Changes API does not return changes

### ISSUE THREAD

**Issue by mattheo-geoffray** [GitLabPHP/Client#450]
### Description
When we call `\Gitlab\Model\MergeRequest::changes` the `$data` will contain the response of 
```
https://gitlab.com/api/v4/projects/xxxxx/merge_requests/yyyy/changes
```
but as it will be injected in a `\Gitlab\Model\MergeRequest` object all data will be lost.

### Actual result
No changes data is return from `\Gitlab\Model\MergeRequest::changes`

### Expected result 
Changes data to be returned in a `\Gitlab\Model\MergeRequest` object or in a new `\Gitlab\Model\MergeRequest\Changes` object to reflect API response

**Comment by m1guelpf** [comment]
PRs welcome
