### ISSUE TITLE
Can't create milestone

### ISSUE THREAD

**Issue by Crazynx** [GitLabPHP/Client#489]
About a few weeks ago my code for creating a milestone stopped working, it would return a 404 project not found error. 
My previous code looked like this:
```
$milestone = $this->gitlabClient->createMilestone('titleOfMilestone', [
                'idOfProject',
            ]);
```
I changed it to something that works, which looks like this:
```
$milestone = $this->gitlabClient->createMilestone('idOfProject', [
                'titleOfMilestone',
            ]);
```
But I can't find this information anywhere in the Gitlab API code. A change in the code would be nice.

**Comment by GrahamCampbell** [comment]
Not sure. I think this is something GitLab broke, rather than something that changed in the library?
