### ISSUE TITLE
Swap model constructor parameters around

### ISSUE THREAD

**Issue by m4tthumphrey** [GitLabPHP/Client#8]
IE

``` php
$project = new Project($client, 1);
```

instead of

``` php
$project = new Project(1, $client);
```

This would make `$client` mandatory but it is always passed anyway so do not see any disadvantages to this.

**Comment by GrahamCampbell** [comment]
I think the plan is to remove models (eventually). We can close this off for now, since any refactoring tasks relating to models is not going to be worth it.
